### PR TITLE
Add support for Arduino Due's software erase hack

### PR DESCRIPTION
**Pull request by Timmmm**
Note: This pull request includes 8devices' samba_improvement branch because that's what I started with and git is stupidly hard to use. Sorry.

----

The Arduino Due's USB-to-Serial interface chip has special code that
will erase and reset the SAM3X8E if you open a 1200 baud connection and
immediately close it. This very simple change adds a command line option
to bossac to do that (the option is '-a'). If you use this option you
must specify the port.

I tested it on Windows and it works fine.

### CODE REVIEW

**Comment by mantas-p** [comment]
Hi Tim,

One commit from 8devices branch was missing here, so git imported too much history here. I added it in separate PR (https://github.com/shumatech/BOSSA/pull/11). Please consider cleaning this PR's  commit history.

**Comment by cmaglie** [comment]
@Timmmm 
I've tried your patch on linux, but it seems to be not working, I think that the DTR signal should be explicitly set, maybe Windows do this automatically.

I was wondering also if feature is something we want in bossac: the 1200-bps hack is very Arduino-sketch specific. Maybe a separate tool only for this can be a better choice (that can be reused also on avrdude)?

**Comment by Timmmm** [comment]
I have now tested this on OSX too and it also seems to not work, so it seems like it only works on Windows for now. I will have a go at getting it to work on all platforms.

As for whether this is worth including, I think it is because a) Arduino is very popular - probably 95% of bossac use is for Arduino, even if the users don't know it, and b) the code changes are very minimal.

It is specific to the Arduino hardware (the USB-to-serial chip specifically), but not the software. I am using an Arduino Due but I ported it to mBed, and this hack is very useful.

**Comment by cmaglie** [comment]
@Timmmm 
I'm closing this for now, feel free to submit another PR when you're ready.

**Comment by kevans91** [comment]
@cmaglie - I also feel this is worth inclusion into BOSSA (hidden behind a flag) for a couple reasons:

1.) I think we've had some timing weirdness in FreeBSD-land between the 1200bps reset in the IDE and BOSSA being able to actually program the board. Offloading this to the software that's actually going to be programming the board would eliminate any of the Java overhead and increase success rate, at least in our neck of the woods.

2.) It would be nice to separate this out of the IDE so that BOSSA can stand apart even more from it. Right now, it's completely feasible to have an Arduino setup that contains everything but the IDE/Java bits, but programming the Due requires being a little more familiar with, for instance, stty(1) to open/close a serial port.

3.) It shouldn't add any real overhead/complexity, maintenance or otherwise, to include this as an optional feature. 

I don't expect @shumatech to care at all about the Arduino-specific points, but if it doesn't add any overhead then I see no reason to object as long as it doesn't bring Arduino problems here. If I were to go ahead and fix this up to work on the different platforms, would it be considered for inclusion?

**Comment by shumatech** [comment]
I'm fine with Arduino specific functionality going into BOSSA master so 
long as the following criteria are met:

1) The functionality is not the default and is enabled through switches 
or other non-obtrusive means
2) The functionality does not impact the performance or reliability of 
the non-Arduino path
3) The functionality is testable by the build maintainer

-Scott

**Comment by kevans91** [comment]
Excellent! Thank you for the clarification. =)

**Pull request closed without merging**
