### PR TITLE
Add arduino 1200bps erase flag (-a)

### PR DESCRIPTION
**Pull request by kevans91**
Upon review of PR #10, I don't think the -a/erase specific bits of it actually had any issues. I isolated those changes and tested on a couple of my FreeBSD boxes, and it works flawlessly and reliably in place of my former script:

```
stty -f /dev/cuaU0 1200
stty stop /dev/cuaU0
bossac -i --port=cuaU0 -U false -e -R`
```

Given that FreeBSD and Linux both use termios bits, I would hazard a guess that this is fine on Linux as well. I do not currently have a build setup to test for Windows, though.

### CODE REVIEW

**Comment by kevans91** [comment]
After playing with it more, I think I understand the problem now and will attempt to fix it. This works for me on a fresh Due consistently, but as soon as I actually flash it with a sketch this no longer works. The only way to solve this is to do a manual reset with the above stty invocations and then I can reprogram my Due.

I will dig a little deeper to figure out what magic might be missing when a sketch is loaded.

**Comment by kevans91** [comment]
I'm not sure why this had worked previously for me, given that 1200 wasn't supported in PosixSerialPort.cpp, but this new version works for me at all times and I've successfully flashed my Due on FreeBSD with just the -a flag multiple times.

This latest revisions adds the 1200 bps support to PosixSerialPort and assets RTS/DTR to what they should be just in case. Also, better error handling if the port fails to open.

**Comment by kevans91** [comment]
Ping @cmaglie; we've been running BOSSA 1.7.0 with the following patch applied to sam/platform.txt: https://svnweb.freebsd.org/ports/head/devel/arduino-core/files/patch-hardware_arduino_sam_platform.txt?view=markup

This has made a marked improvement to reliability in programming the Due, and would allow removal of the 1200bps reset bits from the IDE.

**Comment by shumatech** [comment]
Some feedback on the PR:

- Auto scan is no longer supported so you can remove the option help comment and code checks.  Use the default serial port from the factory if the -p port option is not given.
- Use '-' instead of '_' for long options (Unix convention)
- Add Windows support (see  EscapeCommFunction)
- How would I test this as I do not have an Arduino Due?
- Is there an advantage or limitation in having this in BOSSA rather than the Arduino IDE?

**Comment by kevans91** [comment]
Hi,

I'll address the first three when I get a little bit -- apologies for not catching those when I took over the patch.

How to test- I suppose there is no way off-hand. =) Can I send you a Due?  Once you have it, it can be as simple as `bossac -ai -p ${port}`, IIRC -- BOSSA fails to detect the Due altogether without this or some wrapping `stty` bits that are functionally the same.

The only limitation I can think of is that the Arduino folk are then dependent on the -a flag being kept in BOSSA. The advantage is that it eliminates problems with latency between the IDE doing the 1200bps erase and BOSSA attempting to program the board, as well as problems with Java trying to do serial work.

The problem we've (FreeBSD folk) experienced *seems* to be that Arduino is doing the 1200bps bits right, but there's too much latency before bossac attempts to flash and the flashing fails pretty consistently.

**Comment by kevans91** [comment]
@shumatech: I believe I've addressed your first three concerns now; I have no capacity to test the WinSerialPort changes, but the documentation looked pretty straightforward.

**Comment by kevans91** [comment]
Ping @shumatech: If you'd like, I can send you an Arduino Due so you can test this. Shoot me an email, kevans@FreeBSD.org, if you're interested.

Reproduction steps are pretty easy: bossa will fail to communicate with the board completely without this patch. Supplying -a will allow bossa to communicate/connect.

**Pull request merged**
